### Login USER
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "user",
  "password": "user123"
}

### Login ADMIN
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

### GET productos
GET http://localhost:8080/api/v1/productos?page=0&size=10&sort=nombre,asc
Authorization: Bearer {{tokenUser}}
Accept: application/json

### POST producto
POST http://localhost:8080/api/v1/productos
Authorization: Bearer {{tokenAdmin}}
Content-Type: application/json

{
  "nombre": "Yuca fresca",
  "categoria": "Verduras",
  "stock": 50,
  "precio": 0.60
}

### POST invalido
POST http://localhost:8080/api/v1/productos
Authorization: Bearer {{tokenAdmin}}
Content-Type: application/json

{
  "nombre": "",
  "categoria": "Granos",
  "stock": -1,
  "precio": 0
}

### DELETE producto
DELETE http://localhost:8080/api/v1/productos/1
Authorization: Bearer {{tokenAdmin}}

### DELETE inexistente
DELETE http://localhost:8080/api/v1/productos/9999
Authorization: Bearer {{tokenAdmin}}

### GET sin token
GET http://localhost:8080/api/v1/productos?page=0&size=10

### POST con rol insuficiente
POST http://localhost:8080/api/v1/productos
Authorization: Bearer {{tokenUser}}
Content-Type: application/json

{
  "nombre": "No permitido",
  "categoria": "Otros",
  "stock": 1,
  "precio": 1.00
}
